obstacle_range: 7.5
raytrace_range: 8.5
robot_radius: 0.35
inflation_radius: 0.5
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true, expected_update_rate: 0.3,inf_is_valid: true}
