obstacle_range: 8.0
raytrace_range: 8.0
footprint: [ [-0.3, -0.15], [0.0, -0.15], [0.0, 0.15], [-0.3, 0.15] ]
robot_radius: 0.3
footprint_padding: 0.00

inflation_radius: 0.5
max_obstacle_height: 0.6
min_obstacle_height: 0.0
